task_name: link_pred
gpu: 0
multithreading: False
lr: 0.0001

defaults:
    - _self_
    - dataset: DPPIN-Ito

    - task: link_pred

    - model: DySat

    - optim: adam

    - override hydra/job_logging: colorlog

    - override hydra/hydra_logging: colorlog