evolving: False # If false Model does not considere links that appeared in previous timestamp
score: 'none' # If true, Model considers the score of the links
one_hot: True
name: DGT_STA
pred_next: False
clip_grad: False
link_pred: 
  _target_: dgt.models.DGT_STA
  num_nodes: ${dataset.num_nodes}
  num_features: ${sub:${dataset.timestamp},1}
  num_classes: ${dataset.num_classes}
  time_length: ${dataset.timestamp}
  window: 0
  pred_next: ${model.pred_next}
  spatial_pe: 'none'
  add_temporal_pe: True
  cat_te: True
  lin_te: False
  score: ${model.score}
  decision: 'dot'
  use_cross_attn: False
  flash: False
  performer: false
  light_ca: False
  nhead_ca : 1
  dropout_ca : 0.1
  bias_ca : True
  add_bias_kv : False
  add_zero_attn : False
  dropout_dec: 0.1
  bias_lin_pe: False
  dim_emb: 128
  dim_pe: 0
  add_lin_pe: True
  dim_feedforward: 256
  nhead: 4
  num_layers_trsf: 1
  num_layers_gcn: 2
  aggr: 'last'
  mask_gtoken: False
  temp_pe_drop: 0.1
  one_hot: ${model.one_hot}
  norm_first: False
  undirected: True