evolving: False # If false Model does not considere links that appeared in previous timestamp
one_hot: True
name: DySat
pred_next: False
score: 'none' # If true, Model considers the score of the links
clip_grad: False

node_classif: 
  _target_: dgt.models.DySat
  num_nodes: ${dataset.num_nodes}
  num_features: ${dataset.features_dim}
  num_classes: ${dataset.num_classes}
  time_length: ${dataset.timestamp}
  window: -1
  structural_head_config: [16,8,8]
  structural_layer_config: [128]
  temporal_head_config: [16]
  temporal_layer_config: [128]
  spatial_drop: 0.1
  temporal_drop: 0.5
  residual: True
  neg_weight: 1.0
  aggr: last
  one_hot: ${model.one_hot}
  task_name: 'node_classif'
  
link_pred:
  _target_: dgt.models.DySat
  num_nodes: ${dataset.num_nodes}
  num_features: ${dataset.features_dim}
  num_classes: ${dataset.num_classes}
  time_length: ${dataset.timestamp}
  window: -1
  structural_head_config: [16,8,8]
  structural_layer_config: [128]
  temporal_head_config: [16]
  temporal_layer_config: [128]
  spatial_drop: 0.1
  temporal_drop: 0.5
  residual: True
  neg_weight: 1.0
  undirected: False
  aggr: last
  one_hot: ${model.one_hot}
  task_name: 'link_pred'

node_reg:
  _target_: dgt.models.DySat
  num_nodes: ${dataset.num_nodes}
  num_features: ${dataset.features_dim}
  num_classes: ${dataset.num_classes}
  time_length: ${dataset.timestamp}
  window: -1
  structural_head_config: [16,8,8]
  structural_layer_config: [128]
  temporal_head_config: [16]
  temporal_layer_config: [128]
  spatial_drop: 0.1
  temporal_drop: 0.5
  residual: True
  neg_weight: 1.0
  undirected: False
  aggr: last
  one_hot: ${model.one_hot}
  task_name: 'node_reg'

