evolving: False # If false Model does not considere links that appeared in previous timestamp
one_hot: True
name: GConvLSTM
pred_next: False
clip_grad: False

link_pred:
  _target_: dgt.models.GConvLSTM
  num_nodes: ${dataset.num_nodes}
  num_features: ${sub:${dataset.timestamp},1}
  in_channels: 128
  time_length: ${dataset.timestamp}
  K: 2
  normalization: 'sym'
  bias: true
  one_hot: ${model.one_hot}
  undirected: True