evolving: False # If false Model does not considere links that appeared in previous timestamp
score: 'none' # If true, Model considers the score of the links
one_hot: True
name: LSTMGT
pred_next: False
clip_grad: False
link_pred: 
  _target_: dgt.models.LSTMGT
  num_nodes: ${dataset.num_nodes}
  num_features: ${sub:${dataset.timestamp},1}
  num_classes: ${dataset.num_classes}
  time_length: ${dataset.timestamp}
  window: 5
  spatial_pe: 'rwpe'
  dim_emb: 128
  dim_pe: 12
  dim_feedforward: 512
  nhead: 4
  num_layers_lstm: 1
  one_hot: ${model.one_hot}
  norm_first: False
  undirected: True