evolving: False # If false Model does not considere links that appeared in previous timestamp
score: 'none' # If true, Model considers the score of the links
one_hot: True
name: SLATE
pred_next: False
clip_grad: False
link_pred: 
  _target_: slate.models.SLATE
  num_nodes: ${dataset.num_nodes}
  num_features: ${sub:${dataset.timestamp},1}
  num_classes: ${dataset.num_classes}
  time_length: ${dataset.timestamp}
  window: 1
  pred_next: ${model.pred_next}
  decision: 'dot'
  use_cross_attn: False
  flash: False
  light_ca: False
  nhead_ca : 1
  dropout_ca : 0.1
  bias_ca : True
  add_bias_kv : False
  add_zero_attn : False
  dropout_dec: 0.1
  dim_emb: 128
  dim_pe: 12
  norm_lap: 'sym'
  add_eig_vals: False
  add_vn: False
  remove_isolated: True
  isolated_in_transformer: False
  add_time_connection: False
  p_self_time: 0.5
  bias_lin_pe: False
  add_lin_pe: True
  dim_feedforward: 256
  nhead: 4
  num_layers_trsf: 1
  aggr: 'last'
  one_hot: ${model.one_hot}
  norm_first: False
  undirected: True