
engine:
  epoch: 50
  eval_every: 1
  n_runs: 1
  unbalanced_sampling: True # if True, use weighted sampling in train
  unbalanced_loss: False # If True, use weighted loss
  shuffle_train_loader: True 
  batch_size: 64
  early_stopping: 15

  train_loader:
    _target_: torch.utils.data.DataLoader
    batch_size: ${task.engine.batch_size}
    num_workers: 10
    pin_memory: True
    drop_last: True

  test_loader:
    _target_: torch.utils.data.DataLoader
    batch_size: ${task.engine.batch_size}
    shuffle: False
    num_workers: 10
    pin_memory: True
    drop_last: False


loss: 
  _target_: torch.nn.BCEWithLogitsLoss
  reduction: mean


optimizer: 
  _target_: torch.optim.Adam
  lr: ${lr}
  weight_decay: ${div:${lr},2}
