python dgt/run.py \
 --multirun \
 wandb_conf.name=FAST_Search_Message \
 dataset=DGB-UCI-Message \
 model=DGT_STA \
 gpu=2 \
 lr=0.1,0.01,0.001,0.0001 \
 task.engine.batch_size=1024 \
 task.split=lastk \
 model.evolving=False \
 model.clip_grad=True \
 model.pred_next=False \
 model.link_pred.use_cross_attn=False \
 model.link_pred.bias_lin_pe=False \
 model.link_pred.spatial_pe=rwpe \
 model.link_pred.add_temporal_pe=False \
 model.link_pred.window=2,3,4 \
 model.link_pred.cat_te=True \
 model.link_pred.lin_te=True \
 model.link_pred.add_lin_pe=True \
 model.link_pred.dim_pe=12 \
 model.link_pred.dim_feedforward=1024 \
 model.link_pred.nhead=8 \
 model.link_pred.aggr=last \
 model.link_pred.temp_pe_drop=0.1 \
 model.link_pred.norm_first=True \
 model.link_pred.undirected=True \
 optim.optimizer.weight_decay=5e-7 \
 task.engine.n_runs=1 \
 