python dgt/run.py \
 wandb_conf.name=FASTSupraLap_Test_CAN \
 dataset=DGB-CanParl \
 model=FAST \
 gpu=1 \
 lr=0.0001 \
 task.engine.batch_size=1024 \
 model.evolving=False \
 model.clip_grad=True \
 model.pred_next=False \
 model.link_pred.bias_lin_pe=False \
 model.link_pred.window=2 \
 model.link_pred.use_cross_attn=True \
 model.link_pred.flash=False \
 model.link_pred.light_ca=False \
 model.link_pred.nhead_ca=4 \
 model.link_pred.dropout_ca=0.1 \
 model.link_pred.bias_ca=True \
 model.link_pred.add_bias_kv=True \
 model.link_pred.add_zero_attn=False \
 model.link_pred.add_lin_pe=True\
 model.link_pred.dim_pe=30 \
 model.link_pred.norm_lap=rw \
 model.link_pred.add_eig_vals=False \
 model.link_pred.remove_isolated=True \
 model.link_pred.isolated_in_transformer=True\
 model.link_pred.add_time_connection=False \
 model.link_pred.p_self_time=0.5 \
 model.link_pred.dim_feedforward=1024 \
 model.link_pred.nhead=8 \
 model.link_pred.aggr=mean \
 model.link_pred.norm_first=True \
 model.link_pred.undirected=True \
 optim.optimizer.weight_decay=0 \
 task.engine.n_runs=1 \